// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj3BA5u1NKfAMoCOeH40Qt5T7HhfAdV5Q',
    appId: '1:852719096611:web:b5e0e427fbbf0481757296',
    messagingSenderId: '852719096611',
    projectId: 'akamai-2024',
    authDomain: 'akamai-2024.firebaseapp.com',
    storageBucket: 'akamai-2024.firebasestorage.app',
    measurementId: 'G-RK6HC1E9L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyWpjkr6pQO0LQXrgnEgJv5H-GRxgj-v4',
    appId: '1:852719096611:android:8aa90f072a9f3550757296',
    messagingSenderId: '852719096611',
    projectId: 'akamai-2024',
    storageBucket: 'akamai-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg8WIj97WFHAJvRidVO1Plh4ZiYNclq18',
    appId: '1:852719096611:ios:2adb4002afcf3c4f757296',
    messagingSenderId: '852719096611',
    projectId: 'akamai-2024',
    storageBucket: 'akamai-2024.firebasestorage.app',
    iosBundleId: 'com.example.akamaibot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg8WIj97WFHAJvRidVO1Plh4ZiYNclq18',
    appId: '1:852719096611:ios:2adb4002afcf3c4f757296',
    messagingSenderId: '852719096611',
    projectId: 'akamai-2024',
    storageBucket: 'akamai-2024.firebasestorage.app',
    iosBundleId: 'com.example.akamaibot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj3BA5u1NKfAMoCOeH40Qt5T7HhfAdV5Q',
    appId: '1:852719096611:web:eb512be804c05b36757296',
    messagingSenderId: '852719096611',
    projectId: 'akamai-2024',
    authDomain: 'akamai-2024.firebaseapp.com',
    storageBucket: 'akamai-2024.firebasestorage.app',
    measurementId: 'G-H7DV5TV1TM',
  );

}